# Generated by Django 4.0.3 on 2022-03-22 03:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_name_account_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('group_profile', models.ImageField(blank=True, default='project_profiles/default.jpg', null=True, upload_to='project_profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_profile',
            field=models.ImageField(blank=True, default='project_profiles/default.jpg', null=True, upload_to='group_profiles/'),
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
