# Generated by Django 4.0.3 on 2022-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_group_account_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.account'),
        ),
    ]
