# Generated by Django 4.0.3 on 2022-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_profile',
            field=models.ImageField(blank=True, default='project_profiles/default.jpg', null=True, upload_to='project_profiles/'),
        ),
    ]
