# Generated by Django 4.0.3 on 2022-03-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_project_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
