# Generated by Django 4.0.3 on 2022-03-29 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account_followers_account_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('following', models.ManyToManyField(blank=True, null=True, to='users.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='followers_account',
            field=models.ManyToManyField(blank=True, null=True, to='users.follow'),
        ),
    ]
