# Generated by Django 4.0.3 on 2022-03-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_follow_account_followers_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers_account',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
