# Generated by Django 4.0.3 on 2022-03-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_account_followers_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followers_account',
        ),
        migrations.AddField(
            model_name='account',
            name='followed_accounts',
            field=models.ManyToManyField(blank=True, related_name='follows', to='users.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='follower_accounts',
            field=models.ManyToManyField(blank=True, to='users.account'),
        ),
    ]
