# Generated by Django 4.0.3 on 2022-03-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_linkedin_account'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesg', to='users.account'),
        ),
    ]
