# Generated by Django 4.0.3 on 2022-03-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_groupmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['is_read', 'created']},
        ),
    ]
