# Generated by Django 4.0.3 on 2022-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_groupmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmessage',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
