# Generated by Django 4.0.3 on 2022-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_accountmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
